"""Move every DECISIONS.md entry older than the current week into a weekly archive.

    python scripts/archive_decisions.py --dry-run   # say what would move
    python scripts/archive_decisions.py             # move it, then re-index
    python scripts/archive_decisions.py --today 2026-09-27   # for tests

Weeks run Sunday to Saturday, matching the weekly usage reset, and an archive
file is named by its Sunday: `docs/decisions/2026-09-20.md` holds 09-20 to
09-26. Run it at the start of a week, from the cleanup session.

WHY. DECISIONS.md reached 414 entries and about 300k tokens in ten days, every
two-session merge touched it, and its generated index alone was about 18k
tokens (docs/efficiency_review_2026-09-27.md, change 1). The owner chose a
weekly archive over a monthly one because every entry so far is from
September: a monthly archive would move nothing until October 1.

WHAT IT PROMISES. Entries move VERBATIM - the append-only rule is about the
entries, not the file they sit in - and the script refuses to write unless every
heading it read is still present exactly once across the live file and the
archives, with each moved section byte-identical. An archive file that already
exists (an entry dated last week that landed late) is merged into, newest
first, never overwritten.

AFTER ARCHIVING, a branch that forked before it will conflict on DECISIONS.md.
`scripts/merge_append_only.py` treats an entry already in `docs/decisions/` as
present, so resolving that conflict cannot put archived entries back.
"""
import argparse
import datetime as dt
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "DECISIONS.md"
ARCHIVE = ROOT / "docs" / "decisions"
CHANGES = "\n## Changes\n"
HEADING = re.compile(r"^### (\d{4}-\d{2}-\d{2})\b.*$", re.M)
ANY_HEADING = re.compile(r"^### .+$", re.M)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def week_start(day):
    """The Sunday on or before `day`."""
    return day - dt.timedelta(days=(day.weekday() + 1) % 7)


def split_sections(body, label):
    """-> (lead, [(heading, date, text)]) for a '## Changes' body."""
    found = list(ANY_HEADING.finditer(body))
    lead = body[:found[0].start()] if found else body
    if lead.strip():
        sys.exit(f"{label}: text between '## Changes' and the first entry; resolve by hand")
    out = []
    for i, m in enumerate(found):
        end = found[i + 1].start() if i + 1 < len(found) else len(body)
        dm = HEADING.match(m.group(0))
        if not dm:
            sys.exit(f"{label}: undated heading {m.group(0)!r}; date it or archive by hand")
        out.append((m.group(0), dt.date.fromisoformat(dm.group(1)), body[m.start():end]))
    return lead, out


def archive_header(sunday):
    saturday = sunday + dt.timedelta(days=6)
    return (f"# Decisions log - week of {sunday} (Sunday) to {saturday} (Saturday)\n\n"
            "Archived verbatim from `DECISIONS.md` by `scripts/archive_decisions.py`. "
            "Append-only like the live file: an entry here is never edited, and a "
            "superseding decision goes in `DECISIONS.md` as a new entry. Newest first.\n\n"
            "---\n\n"
            "<!-- INDEX:START - generated by scripts/decisions_index.py; do not hand-edit -->\n"
            "<!-- INDEX:END -->\n")


def split_file(text, label):
    if CHANGES not in text:
        sys.exit(f"{label}: no '## Changes' heading")
    cut = text.index(CHANGES) + len(CHANGES)
    lead, sections = split_sections(text[cut:], label)
    return text[:cut] + lead, sections


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--today", type=dt.date.fromisoformat, default=dt.date.today())
    args = ap.parse_args()

    cutoff = week_start(args.today)
    text = DECISIONS.read_text(encoding="utf-8")
    head, sections = split_file(text, "DECISIONS.md")
    keep = [s for s in sections if s[1] >= cutoff]
    move = [s for s in sections if s[1] < cutoff]
    if not move:
        print(f"nothing older than {cutoff} (this week's Sunday); {len(keep)} entries stay")
        return

    by_week = {}
    for s in move:
        by_week.setdefault(week_start(s[1]), []).append(s)

    before = [h for h, _, _ in sections]
    archived_before = {}
    for f in sorted(ARCHIVE.glob("*.md")):
        for h in ANY_HEADING.findall(f.read_text(encoding="utf-8")):
            archived_before[h] = f.name
    clash = [h for h in before if h in archived_before]
    if clash:
        sys.exit(f"already archived AND still live - resolve by hand: {clash[:3]}")

    writes = {}
    for sunday, new in sorted(by_week.items()):
        path = ARCHIVE / f"{sunday}.md"
        if path.exists():
            a_head, existing = split_file(path.read_text(encoding="utf-8"), path.name)
        else:
            a_head, existing = archive_header(sunday) + "\n## Changes\n\n", []
        # Late arrivals first within a date: they were written after what is there.
        merged = sorted(new + existing, key=lambda s: s[1], reverse=True)
        writes[path] = a_head + "".join(s[2] if s[2].endswith("\n\n") else s[2].rstrip("\n") + "\n\n"
                                        for s in merged).rstrip("\n") + "\n"
        print(f"  {path.relative_to(ROOT).as_posix()}: +{len(new)} "
              f"({len(existing)} already there)")

    live = head + "".join(s[2] for s in keep)
    if not live.endswith("\n"):
        live += "\n"

    # Refuse unless every heading is present exactly once, and every moved
    # section's text survives byte for byte.
    after = ANY_HEADING.findall(live)
    for body in writes.values():
        after += ANY_HEADING.findall(body)
    untouched = [f for f in ARCHIVE.glob("*.md") if f not in writes]
    for f in untouched:
        after += ANY_HEADING.findall(f.read_text(encoding="utf-8"))
    want = before + list(archived_before)
    if sorted(after) != sorted(want):
        missing = set(want) - set(after)
        extra = [h for h in set(after) if after.count(h) > 1]
        sys.exit(f"REFUSING TO WRITE: missing {sorted(missing)[:3]}, duplicated {extra[:3]}")
    for s in move:
        target = writes[ARCHIVE / f"{week_start(s[1])}.md"]
        if s[2].rstrip("\n") not in target:
            sys.exit(f"REFUSING TO WRITE: {s[0]!r} would not move verbatim")

    print(f"{len(move)} entries older than {cutoff} -> {len(writes)} archive file(s); "
          f"{len(keep)} stay in DECISIONS.md")
    if args.dry_run:
        print("--dry-run: nothing written")
        return
    ARCHIVE.mkdir(parents=True, exist_ok=True)
    for path, body in writes.items():
        path.write_text(body, encoding="utf-8", newline="\n")
    DECISIONS.write_text(live, encoding="utf-8", newline="\n")

    sys.path.insert(0, str(ROOT / "scripts"))
    import decisions_index
    decisions_index.write_all()
    print("indexes regenerated. Commit DECISIONS.md and docs/decisions/ together.")


if __name__ == "__main__":
    main()
