"""Watch the weekly DECISIONS archive survive a merge - and watch it fail without the guard.

    python scripts/archive_decisions_selftest.py

Builds a throwaway git repository in a temp folder, touches nothing here:

  1. A base DECISIONS.md with entries from two past weeks.
  2. Branch `late` forks and appends this week's entry at the top.
  3. master runs scripts/archive_decisions.py, moving every entry to docs/decisions/.
  4. `late` merges master, conflicts on DECISIONS.md, and resolves it with
     scripts/merge_append_only.py.

PASS means: the guarded resolution keeps the new entry, puts no archived entry
back, and `decisions_index.py --check` is clean; AND the same merge with the
guard switched off (`--archive-glob ""`) does put them back and `--check`
catches it. The second half is the control - a guard that cannot be seen to
fail proves nothing.
"""
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = ["archive_decisions.py", "decisions_index.py", "merge_append_only.py"]

BASE = """# Decisions log

Preamble.

---

<!-- INDEX:START - generated by scripts/decisions_index.py; do not hand-edit -->
<!-- INDEX:END -->

## Changes

### 2026-09-24 - Second week, later entry

- **Body of the 09-24 entry.**

### 2026-09-21 - Second week, first entry

- **Body of the 09-21 entry.**

### 2026-09-18 - First week

- **Body of the 09-18 entry.**
"""
NEW = "### 2026-09-27 - This week's entry, written on a late branch\n\n- **New.**\n\n"
OLD = ["2026-09-24 - Second week", "2026-09-21 - Second week", "2026-09-18 - First week"]


def run(repo, *cmd, ok=True):
    # A git hook runs with GIT_DIR, GIT_INDEX_FILE and friends pointing at the
    # REAL repository; left in place they make every command here act on it
    # instead of the throwaway one. Found when the pre-push hook first ran this.
    env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
    p = subprocess.run(list(cmd), cwd=repo, capture_output=True, text=True,
                       encoding="utf-8", errors="replace", env=env)
    if ok and p.returncode:
        raise SystemExit(f"setup failed: {' '.join(cmd)}\n{p.stdout}{p.stderr}")
    return p


def scenario(root, guard):
    repo = Path(root) / ("guarded" if guard else "unguarded")
    (repo / "scripts").mkdir(parents=True)
    for s in SCRIPTS:
        shutil.copy(HERE / s, repo / "scripts" / s)
    py = sys.executable
    run(repo, "git", "init", "-q", "-b", "master")
    run(repo, "git", "config", "user.email", "selftest@example.invalid")
    run(repo, "git", "config", "user.name", "selftest")
    run(repo, "git", "config", "core.autocrlf", "false")
    (repo / "DECISIONS.md").write_text(BASE, encoding="utf-8", newline="\n")
    run(repo, py, "scripts/decisions_index.py")
    run(repo, "git", "add", "-A")
    run(repo, "git", "commit", "-q", "-m", "base")

    run(repo, "git", "checkout", "-q", "-b", "late")
    text = (repo / "DECISIONS.md").read_text(encoding="utf-8")
    text = text.replace("## Changes\n\n", "## Changes\n\n" + NEW, 1)
    (repo / "DECISIONS.md").write_text(text, encoding="utf-8", newline="\n")
    run(repo, py, "scripts/decisions_index.py")
    run(repo, "git", "commit", "-q", "-am", "late entry")

    run(repo, "git", "checkout", "-q", "master")
    run(repo, py, "scripts/archive_decisions.py", "--today", "2026-09-27")
    run(repo, "git", "add", "-A")
    run(repo, "git", "commit", "-q", "-m", "archive")

    run(repo, "git", "checkout", "-q", "late")
    merged = run(repo, "git", "merge", "master", ok=False)
    if merged.returncode == 0:
        return "the merge did not conflict, so the scenario tests nothing"
    extra = [] if guard else ["--archive-glob", ""]
    res = run(repo, py, "scripts/merge_append_only.py", "DECISIONS.md", *extra, ok=False)
    if res.returncode:
        return f"merge_append_only refused: {res.stdout}{res.stderr}".strip()
    run(repo, py, "scripts/decisions_index.py", ok=False)
    live = (repo / "DECISIONS.md").read_text(encoding="utf-8")
    back = [h for h in OLD if h in live]
    check = run(repo, py, "scripts/decisions_index.py", "--check", ok=False)
    return {"new_kept": "late branch" in live, "put_back": back,
            "check_rc": check.returncode}


def main():
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as root:
        guarded = scenario(root, guard=True)
        unguarded = scenario(root, guard=False)
    failures = []
    if not isinstance(guarded, dict):
        failures.append(f"guarded: {guarded}")
    elif not guarded["new_kept"] or guarded["put_back"] or guarded["check_rc"]:
        failures.append(f"guarded merge went wrong: {guarded}")
    if not isinstance(unguarded, dict):
        failures.append(f"control: {unguarded}")
    elif not unguarded["put_back"] or unguarded["check_rc"] == 0:
        failures.append(f"control did NOT reproduce the failure, so the guard is unproven: "
                        f"{unguarded}")
    if failures:
        print("FAIL\n  " + "\n  ".join(failures))
        return 1
    print(f"2 of 2 cases behaved as intended: guarded keeps the new entry and restores "
          f"nothing; unguarded restores {len(unguarded['put_back'])} archived entries "
          f"and --check catches them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
