"""Regenerate the navigation index at the top of DECISIONS.md and of every
weekly archive in docs/decisions/.

    python scripts/decisions_index.py          # rewrite the indexes
    python scripts/decisions_index.py --check  # fail if one is stale, or if an
                                               # entry is in two files at once

Since 2026-09-27 entries older than the current week move to
`docs/decisions/<Sunday>.md` (`scripts/archive_decisions.py`). DECISIONS.md's
index then lists this week's entries plus one line per archived week. An entry
heading found in two files - live and archived, or two archives - fails
`--check`: it is what a merge that put archived entries back looks like.

WHY
---
`DECISIONS.md` is append-only and must stay that way - it is the reasoning
trail, and an edited entry is a lost one. But it is now **5,421 lines and
57,609 words across 100 dated sections**, and `pipeline/drift_check.py` ends
every run by telling you to "compare the step row counts above against the
latest baseline entry in DECISIONS.md". Finding that by eye is the friction
this removes.

The index is GENERATED, between two markers, so it cannot go stale the way a
hand-written table of contents would. It touches no entry: the append-only rule
is about the entries, and this is navigation above them.

Anchors follow GitHub's heading-slug rules so the links work on the web view as
well as in an editor.
"""

import argparse
import re
import sys
from pathlib import Path

DECISIONS = Path(__file__).parent.parent / "DECISIONS.md"
ARCHIVE = DECISIONS.parent / "docs" / "decisions"
START = "<!-- INDEX:START - generated by scripts/decisions_index.py; do not hand-edit -->"
END = "<!-- INDEX:END -->"
HEADING = re.compile(r"^### (.+?)\s*$", re.M)


def slugify(text):
    """GitHub's anchor rules: lowercase, drop punctuation, spaces to hyphens."""
    s = text.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    return re.sub(r"\s+", "-", s.strip())


def build(text, archives=()):
    """The index block for one file; `archives` lists (path, count) for the live one."""
    sections = []
    for m in HEADING.finditer(text):
        title = m.group(1).strip()
        # skip headings inside the index block itself
        if title.startswith("Index"):
            continue
        date = ""
        dm = re.match(r"(\d{4}-\d{2}-\d{2})\s*-\s*(.*)", title)
        if dm:
            date, rest = dm.group(1), dm.group(2)
        else:
            rest = title
        sections.append((date, rest, slugify(title)))

    by_date = {}
    for date, rest, anchor in sections:
        by_date.setdefault(date or "(undated)", []).append((rest, anchor))

    lines = [
        START,
        "",
        "## Index",
        "",
        f"**{len(sections)} entries.** Generated - run "
        "`python scripts/decisions_index.py` after appending, or "
        "`--check` to verify. Newest first, matching the file itself.",
        "",
    ]
    for date in sorted(by_date, reverse=True):
        lines.append(f"**{date}**")
        lines.append("")
        for rest, anchor in by_date[date]:
            lines.append(f"- [{rest}](#{anchor})")
        lines.append("")
    if archives:
        lines.append("**Archived weeks** (`scripts/archive_decisions.py`), newest first:")
        lines.append("")
        for rel, count in archives:
            lines.append(f"- [week of {Path(rel).stem}]({rel}) - {count} entries")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def files():
    return [DECISIONS] + sorted(ARCHIVE.glob("*.md"), reverse=True)


def indexed(path, text, archives=()):
    """-> the file's text with its index regenerated."""
    index = build(text, archives)
    if START in text and END in text:
        return text[:text.index(START)] + index + text[text.index(END) + len(END):]
    marker = "\n---\n"
    if marker not in text:
        sys.exit(f"{path.name}: expected a '---' after the preamble.")
    cut = text.index(marker) + len(marker)
    return text[:cut] + "\n" + index + "\n" + text[cut:]


def duplicates():
    seen, dup = {}, []
    for f in files():
        for h in HEADING.findall(f.read_text(encoding="utf-8")):
            if h.startswith("Index"):
                continue
            if h in seen:
                dup.append(f"{h[:70]!r} in {seen[h]} and {f.name}")
            seen.setdefault(h, f.name)
    return dup


def plan():
    """-> [(path, old text, new text)] for every index file."""
    archives = [(f"docs/decisions/{f.name}",
                 len([h for h in HEADING.findall(f.read_text(encoding="utf-8"))
                      if not h.startswith("Index")]))
                for f in files()[1:]]
    out = []
    for f in files():
        text = f.read_text(encoding="utf-8")
        out.append((f, text, indexed(f, text, archives if f == DECISIONS else ())))
    return out


def write_all():
    for f, old, new in plan():
        if new != old:
            # newline="\n" or this writes CRLF on Windows and the working copy
            # then differs byte-for-byte from the blob git stores, while `git
            # status` reads clean because git normalises on commit. That mismatch
            # hid a CRLF-only change to .claude/agents/deploy-verify.md on
            # 2026-09-22 and left the agent unregistered for a whole session.
            f.write_text(new, encoding="utf-8", newline="\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if an index is stale, changing nothing")
    args = ap.parse_args()

    dup = duplicates()
    if dup:
        sys.exit(f"{len(dup)} entry heading(s) in two files - a merge put archived "
                 f"entries back? Remove the live copy:\n  " + "\n  ".join(dup[:5]))

    if args.check:
        stale = [f.name for f, old, new in plan() if new != old]
        n = len(HEADING.findall(DECISIONS.read_text(encoding="utf-8")))
        if stale:
            sys.exit(f"DECISIONS.md index is STALE in {', '.join(stale)} ({n} headings "
                     f"found). Run: python scripts/decisions_index.py")
        print(f"index is current ({n} entries live, {len(files()) - 1} archived week(s))")
        return

    write_all()
    live = len([h for h in HEADING.findall(DECISIONS.read_text(encoding="utf-8"))
                if not h.startswith("Index")])
    print(f"wrote index: {live} entries linked, {len(files()) - 1} archived week(s)")


if __name__ == "__main__":
    # A Windows console defaults to cp1252 and raises UnicodeEncodeError on
    # Hangul, Han and kana, and on Czech and Latvian letters (brief_check.py
    # crashed on a Korean claim, 2026-09-27). UTF-8 regardless of the console.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    main()
