"""Regenerate the navigation index at the top of DECISIONS.md.

    python scripts/decisions_index.py          # rewrite the index
    python scripts/decisions_index.py --check  # fail if it is stale (CI-style)

WHY
---
`DECISIONS.md` is append-only and must stay that way - it is the reasoning
trail, and an edited entry is a lost one. But it is now **5,421 lines and
57,609 words across 100 dated sections**, and `pipeline/drift_check.py` ends
every run by telling you to "compare the step row counts above against the
latest baseline entry in DECISIONS.md". Finding that by eye is the friction
this removes.

The index is GENERATED, between two markers, so it cannot go stale the way a
hand-written table of contents would. It touches no entry: the append-only rule
is about the entries, and this is navigation above them.

Anchors follow GitHub's heading-slug rules so the links work on the web view as
well as in an editor.
"""

import argparse
import re
import sys
from pathlib import Path

DECISIONS = Path(__file__).parent.parent / "DECISIONS.md"
START = "<!-- INDEX:START - generated by scripts/decisions_index.py; do not hand-edit -->"
END = "<!-- INDEX:END -->"
HEADING = re.compile(r"^### (.+?)\s*$", re.M)


def slugify(text):
    """GitHub's anchor rules: lowercase, drop punctuation, spaces to hyphens."""
    s = text.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    return re.sub(r"\s+", "-", s.strip())


def build(text):
    sections = []
    for m in HEADING.finditer(text):
        title = m.group(1).strip()
        # skip headings inside the index block itself
        if title.startswith("Index"):
            continue
        date = ""
        dm = re.match(r"(\d{4}-\d{2}-\d{2})\s*-\s*(.*)", title)
        if dm:
            date, rest = dm.group(1), dm.group(2)
        else:
            rest = title
        sections.append((date, rest, slugify(title)))

    by_date = {}
    for date, rest, anchor in sections:
        by_date.setdefault(date or "(undated)", []).append((rest, anchor))

    lines = [
        START,
        "",
        "## Index",
        "",
        f"**{len(sections)} entries.** Generated - run "
        "`python scripts/decisions_index.py` after appending, or "
        "`--check` to verify. Newest first, matching the file itself.",
        "",
    ]
    for date in sorted(by_date, reverse=True):
        lines.append(f"**{date}**")
        lines.append("")
        for rest, anchor in by_date[date]:
            lines.append(f"- [{rest}](#{anchor})")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the index is stale, changing nothing")
    args = ap.parse_args()

    text = DECISIONS.read_text(encoding="utf-8")
    index = build(text)

    if START in text and END in text:
        before = text[:text.index(START)]
        after = text[text.index(END) + len(END):]
        new = before + index + after
    else:
        # First run: insert after the preamble's horizontal rule, so the
        # explanation of what this file IS still comes first.
        marker = "\n---\n"
        if marker not in text:
            sys.exit("DECISIONS.md: expected a '---' after the preamble.")
        cut = text.index(marker) + len(marker)
        new = text[:cut] + "\n" + index + "\n" + text[cut:]

    if args.check:
        if new != text:
            n = len(HEADING.findall(text))
            sys.exit(f"DECISIONS.md index is STALE ({n} headings found). "
                     f"Run: python scripts/decisions_index.py")
        print(f"index is current ({len(HEADING.findall(text))} entries)")
        return

    DECISIONS.write_text(new, encoding="utf-8")
    count = index.count("\n- [")
    print(f"wrote index: {count} entries linked")


if __name__ == "__main__":
    main()
