"""README's "Mapped so far" list, generated from app/cities.py.

    python scripts/readme_cities.py           # rewrite the list
    python scripts/readme_cities.py --check   # fail if it is stale (check_all runs this)

WHY. The README is the project's public front door on GitHub, and its city
list was hand-kept. On 2026-09-27 it was missing about twenty live cities
(every Taiwanese and Brazilian city, Hong Kong, Riga, Copenhagen, Prague,
Amsterdam, Rotterdam and Rome among them) while `app/cities.py` listed all 49.
A list that restates
another list drifts; one generated from it cannot.

The list sits between two markers and is grouped by `country`, in the order
countries first appear in `app/cities.py` (the order they were built). City
names are exactly the `name` field. `cities.py` is read with `ast`, not
imported, so this runs without streamlit installed.
"""
import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
CITIES = ROOT / "app" / "cities.py"
START = "<!-- CITIES:START - generated by scripts/readme_cities.py from app/cities.py; do not hand-edit -->"
END = "<!-- CITIES:END -->"

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def cities():
    tree = ast.parse(CITIES.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == "CITIES" for t in node.targets):
            out = []
            for entry in node.value.elts:
                d = {k.value: v for k, v in zip(entry.keys, entry.values)
                     if isinstance(k, ast.Constant)}
                out.append((ast.literal_eval(d["country"]), ast.literal_eval(d["name"])))
            return out
    sys.exit("app/cities.py: no CITIES list found")


def block():
    by_country = {}
    for country, name in cities():
        by_country.setdefault(country, []).append(name)
    lines = [START]
    for country, names in by_country.items():
        lines.append(f"- **{country}:** {', '.join(names)}")
    lines.append(END)
    n = sum(len(v) for v in by_country.values())
    return "\n".join(lines), n, len(by_country)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        sys.exit("README.md has no CITIES markers - add them around the city list once")
    new_block, n, countries = block()
    new = text[:text.index(START)] + new_block + text[text.index(END) + len(END):]
    if args.check:
        if new != text:
            sys.exit(f"README.md's city list is STALE against app/cities.py ({n} cities, "
                     f"{countries} countries). Run: python scripts/readme_cities.py")
        print(f"OK - README lists all {n} cities in {countries} countries, as app/cities.py does")
        return
    README.write_text(new, encoding="utf-8", newline="\n")
    print(f"wrote README's city list: {n} cities in {countries} countries")


if __name__ == "__main__":
    main()
