"""Every surface the app renders, read from the code - the inventory a review
lane works from.

    python scripts/rendered_surfaces.py            # print it
    python scripts/rendered_surfaces.py --write    # rewrite docs/rendered_surfaces.md
    python scripts/rendered_surfaces.py --check    # fail if that file is stale (check_all)

Lesson 3 of the 2026-09-30 mega-review (docs/review_lanes_2026-09-30.md):
"list every rendered surface in the lane doc". The About page renders
docs/data_sources/*.md verbatim, no lane's list said so, and a barred brand
reached it. A hand-kept list goes stale with the next page; this one is
derived:

  * every page under app/ (the Overview, each city page, the fixed pages),
    with its URL path, the city it names and the city's slug;
  * what each city page shows besides its own text: its map
    (outputs/<slug>/heatmap.html), the station-scope table read from
    outputs/<slug>/excluded_stations.csv, the caption's dates from
    outputs/<slug>/provenance.json, and the site notices
    (components.render_site_notices);
  * every doc a page renders ("docs" / "<file>" built in app/, plus each
    per-country file the About page globs) and every app/*.json.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "rendered_surfaces.md"
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

SLUG_RE = re.compile(r"from pipeline\.([a-z_]+)\.config import")
NAV_RE = re.compile(r'render_city_nav\("([^"]+)"\)')
DOCS_RE = re.compile(r'"docs"\s*/\s*"([^"]+)"')
JSON_RE = re.compile(r'"([a-z_]+\.json)"')


def url_path(page):
    """Streamlit's URL for a page file: the name without its number prefix."""
    return "/" + re.sub(r"^\d+_", "", page.stem)


def page_order(p):
    """Streamlit's order: numbered pages by number, then unnumbered ones (the
    three info pages since 2026-10-02) by name."""
    m = re.match(r"\d+", p.name)
    return (0, int(m.group()), p.name) if m else (1, 0, p.name)


def pages(root=ROOT):
    out = []
    for p in sorted((root / "app" / "pages").glob("*.py"), key=page_order):
        text = p.read_text(encoding="utf-8")
        slug = SLUG_RE.search(text)
        nav = NAV_RE.search(text)
        out.append({
            "file": p.relative_to(root).as_posix(),
            "url": url_path(p),
            "city": nav.group(1) if nav else None,
            "slug": slug.group(1) if slug else None,
            "docs": sorted(set(DOCS_RE.findall(text))),
            "json": sorted(set(JSON_RE.findall(text))),
            "notices": "render_site_notices" in text,
            "scope_rows": "scope_rows" in text,
        })
    return out


def render(root=ROOT):
    ps = pages(root)
    city = [p for p in ps if p["slug"]]
    fixed = [p for p in ps if not p["slug"]]
    docs = sorted({d for p in ps for d in p["docs"]})
    country = sorted((root / "docs" / "data_sources").glob("*.md")) \
        if "data_sources.md" in docs else []
    overview = (root / "app" / "Overview.py").read_text(encoding="utf-8")
    app_json = sorted(p.name for p in (root / "app").glob("*.json"))
    lines = [
        "# Rendered surfaces",
        "",
        "**Generated by `scripts/rendered_surfaces.py --write`; do not hand-edit.**",
        "`check_all` fails when it is stale. Every surface the deployed app shows,",
        "read from the code, so a review lane can divide them up and miss none",
        "(review lesson 3, `docs/review_lanes_2026-09-30.md`). The lane kit is",
        "`docs/review_lane_kit.md`.",
        "",
        f"**{len(city)} city pages, {len(fixed)} fixed pages and the Overview; "
        f"{len(docs) + len(country)} rendered docs; {len(app_json)} app data files.**",
        "",
        "## The Overview (`/`)",
        "",
        "`app/Overview.py`: the macro map (every city's dot, label and tooltip from",
        "`app/cities.py`; the legend; the region selector), its caption arithmetic,",
        "the city list, and "
        + ("the site notices." if "render_site_notices" in overview else "no site notices."),
        "Data: " + ", ".join(f"`app/{j}`" for j in sorted(set(JSON_RE.findall(overview)))
                             if (root / "app" / j).exists()) + ".",
        "",
        "## Fixed pages",
        "",
        "| URL | File | Renders |",
        "|---|---|---|",
    ]
    for p in fixed:
        what = [f"`docs/{d}`" for d in p["docs"]]
        if "data_sources.md" in p["docs"]:
            what.append(f"every `docs/data_sources/*.md` ({len(country)})")
        what += [f"`app/{j}`" for j in p["json"] if (root / "app" / j).exists()]
        if p["scope_rows"]:
            what.append("every city's `outputs/<slug>/excluded_stations.csv` (`app/station_scope.py`)")
        if p["notices"]:
            what.append("site notices")
        lines.append(f"| `{p['url']}` | `{p['file']}` | {', '.join(what) or 'its own text'} |")
    lines += [
        "",
        "Rendered docs, all of them reader-facing: "
        + ", ".join(f"`docs/{d}`" for d in docs) + ("; " if country else "")
        + ", ".join(f"`{c.relative_to(root).as_posix()}`" for c in country) + ".",
        "",
        "## City pages",
        "",
        "Each shows its own text, its caption (dates from",
        "`outputs/<slug>/provenance.json`), its map `outputs/<slug>/heatmap.html`,",
        "the city switcher, and the site notices (`components.render_site_notices`).",
        "Its station scope (`outputs/<slug>/excluded_stations.csv`) is shown on What",
        "Is Excluded, and its in-ring share on Why the Maps Differ.",
        "",
        "| URL | City | Slug | Notices |",
        "|---|---|---|---|",
    ]
    for p in city:
        lines.append(f"| `{p['url']}` | {p['city'] or '—'} | `{p['slug']}` | "
                     f"{'✓' if p['notices'] else '**none**'} |")
    lines.append("")
    return "\n".join(lines)


def main():
    text = render()
    if "--write" in sys.argv:
        OUT.write_bytes(text.encode("utf-8"))
        print(f"wrote {OUT.relative_to(ROOT)}")
    elif "--check" in sys.argv:
        cur = OUT.read_bytes().decode("utf-8").replace("\r\n", "\n") if OUT.exists() else ""
        if cur != text:
            print(f"FAIL - {OUT.relative_to(ROOT)} is stale: run "
                  f"python scripts/rendered_surfaces.py --write")
            sys.exit(1)
        n = text.count("\n| `/")
        print(f"OK - {OUT.relative_to(ROOT)} lists every page ({n}) the app renders, current")
    else:
        print(text)


if __name__ == "__main__":
    main()
