"""Every built city's ring edges and in-ring share, as docs/ring_rules.md (owner, 2026-09-29:
"save these tables for future use").

    python scripts/ring_rules_table.py            # print the tables
    python scripts/ring_rules_table.py --write    # regenerate docs/ring_rules.md
    python scripts/ring_rules_table.py --check    # exit 1 if docs/ring_rules.md is stale

Nothing here is hand-kept except WHY_SMALL, the reason each deviating city gave in its
own config. The edges come from each city's `pipeline/<slug>/config.py`
(`RING_EDGES_MILES`), the shares from `app/ring_shares.json`, which
`scripts/check_ring_shares.py` keeps true to the committed maps; run that first
after a re-render. A city with smaller rings and no WHY_SMALL entry is printed
as "reason not recorded here", so a new one shows up rather than hiding.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "app"))
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
from cities import CITIES  # noqa: E402
from station_scope import slug  # noqa: E402

OUT = ROOT / "docs" / "ring_rules.md"
STANDARD = [0.0, 0.1, 0.2, 0.3, 0.6]
# Each city's own reason, from its config's comment on RING_EDGES_MILES.
WHY_SMALL = {
    "paris": "399 m median station gap",
    "marseille": "341 m median station gap",
    "new_york": "about 0.3 mi between Manhattan stations",
    "oslo": "465 m median station gap",
    "rennes": "541 m median station gap",
    "toulouse": "525 m median station gap",
    "lille": "501 m median station gap",
}
BANDS = [(0.95, "Over 95%"), (0.80, "80–95%"), (0.60, "60–80%"), (0.40, "40–60%"), (0.0, "Under 40%")]


def edges_of(city_slug):
    cfg = ROOT / "pipeline" / city_slug / "config.py"
    if not cfg.exists():
        return None
    m = re.search(r"^RING_EDGES_MILES\s*=\s*\[([^\]]*)\]", cfg.read_text(encoding="utf-8"), re.M)
    return [float(x) for x in m.group(1).split(",")] if m else None


def rows():
    shares = json.loads((ROOT / "app" / "ring_shares.json").read_text(encoding="utf-8"))
    out = []
    for c in CITIES:
        s = slug(c["page"])
        if s not in shares:
            continue
        v = shares[s]
        out.append({"name": c["name"], "slug": s, "edges": edges_of(s),
                    "share": v["in_ring"] / v["all"], "in_ring": v["in_ring"], "all": v["all"]})
    return sorted(out, key=lambda r: -r["share"])


def mi(edges):
    return " / ".join(f"{e:g}" for e in edges[1:]) + " mi" if edges else "not found in config"


def render():
    rs = rows()
    std = [r for r in rs if r["edges"] == STANDARD]
    dev = [r for r in rs if r["edges"] != STANDARD]
    lines = [
        "# Ring rules of the built cities",
        "",
        "**Generated by `python scripts/ring_rules_table.py --write`; do not edit by hand.**",
        "Edges come from each city's `pipeline/<slug>/config.py`, shares from",
        "`app/ring_shares.json` (storefronts inside the rings over all storefronts the",
        "map carries, read from the committed maps). Regenerate after any city lands",
        "or re-renders.",
        "",
        f"**{len(rs)} built cities: {len(std)} on the standard rings "
        f"({mi(STANDARD)}), {len(dev)} on smaller ones.**",
        "",
        "**The rule for smaller rings is station spacing, not coverage**: where the",
        "median gap between stations is about 550 m or less, a 0.6 mi outer ring",
        "reaches two stations deep and the rings merge into one mass, so the edges",
        "are halved (New York's ground, 2026-09-21; Paris, Marseille, Toulouse,",
        "Lille, Rennes and Oslo on the same measurement). No city has been",
        "re-ringed for a high in-ring share: the cities over 95% below keep the",
        "standard rings.",
        "",
        "## Cities on smaller rings",
        "",
        "| City | Rings | In-ring share | Why (the city's config) |",
        "|---|---|---|---|",
    ]
    for r in dev:
        lines.append(f"| {r['name']} | {mi(r['edges'])} | {r['share']:.1%} | "
                     f"{WHY_SMALL.get(r['slug'], 'reason not recorded here: read its config')} |")
    lines += ["", f"## Cities on the standard rings ({mi(STANDARD)}), by in-ring share", "",
              "| In-ring share | Cities |", "|---|---|"]
    for i, (floor, label) in enumerate(BANDS):
        ceil = BANDS[i - 1][0] if i else 1.01
        group = [r for r in std if floor <= r["share"] < ceil]
        if group:
            names = ", ".join(f"{r['name']} {r['share'] * 100:.1f}" for r in group)
            lines.append(f"| **{label}** ({len(group)}) | {names} |")
    lines += ["", "## Every city", "", "| City | Rings | In ring | All | Share |", "|---|---|---|---|---|"]
    for r in rs:
        lines.append(f"| {r['name']} | {mi(r['edges'])} | {r['in_ring']:,} | {r['all']:,} | {r['share']:.1%} |")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.write:
        OUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUT.relative_to(ROOT)}")
    elif a.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print(f"PROBLEM: {OUT.relative_to(ROOT)} is stale - run python scripts/ring_rules_table.py --write")
            return 1
        print(f"OK - {OUT.relative_to(ROOT)} is current")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
