"""The coverage sweep's Europe universe, hand-curated 2026-10-03.

One row per city served: (city, country, system, aliases, note). Note codes:
"H" heritage or tourist only, "S" satellite of a core city, "U" under
construction or not open, "" normal. Built from Wikipedia's tram and
light-rail and metro lists (`parse_wiki_tram.py`) plus satellites; see
`docs/coverage_sweep/README.md`. France is in `universe_france.py`.
"""
U = [
# Germany
("Augsburg","Germany","Trams (5 lines)",["Augsburg"],""),
("Bad Schandau","Germany","Kirnitzschtal tramway",["Bad Schandau","Kirnitzschtal"],"H"),
("Berlin","Germany","U-Bahn, S-Bahn, trams",["Berlin"],""),
("Bielefeld","Germany","Stadtbahn",["Bielefeld"],""),
("Bochum","Germany","Stadtbahn U35 + trams (Bogestra)",["Bochum"],""),
("Gelsenkirchen","Germany","Bogestra trams + Stadtbahn",["Gelsenkirchen"],""),
("Bonn","Germany","Stadtbahn + trams",["Bonn"],""),
("Brandenburg an der Havel","Germany","Trams",["Brandenburg an der Havel","Brandenburg/Havel"],""),
("Braunschweig","Germany","Trams",["Braunschweig","Brunswick"],""),
("Bremen","Germany","Trams",["Bremen"],""),
("Chemnitz","Germany","Trams / Chemnitz model",["Chemnitz"],""),
("Cologne","Germany","Stadtbahn",["Cologne","Köln","Koln","Koeln"],""),
("Cottbus","Germany","Trams",["Cottbus"],""),
("Darmstadt","Germany","Trams",["Darmstadt"],""),
("Dessau-Roßlau","Germany","Trams",["Dessau"],""),
("Dortmund","Germany","Stadtbahn",["Dortmund"],""),
("Dresden","Germany","Trams",["Dresden"],""),
("Duisburg","Germany","Trams + Stadtbahn U79",["Duisburg"],""),
("Düsseldorf","Germany","Stadtbahn + trams",["Düsseldorf","Dusseldorf","Duesseldorf"],""),
("Erfurt","Germany","Stadtbahn (trams)",["Erfurt"],""),
("Essen","Germany","Stadtbahn + trams",["Essen"],""),
("Frankfurt am Main","Germany","U-Bahn + trams",["Frankfurt am Main","Frankfurt"],""),
("Frankfurt (Oder)","Germany","Trams",["Frankfurt (Oder)","Frankfurt an der Oder","Frankfurt/Oder"],""),
("Freiburg im Breisgau","Germany","Trams",["Freiburg"],""),
("Gera","Germany","Trams",["Gera"],""),
("Görlitz","Germany","Trams",["Görlitz","Gorlitz"],""),
("Gotha","Germany","Trams + Thüringerwaldbahn",["Gotha"],""),
("Halberstadt","Germany","Trams",["Halberstadt"],""),
("Halle (Saale)","Germany","Trams",["Halle (Saale)","Halle an der Saale","Halle"],""),
("Hamburg","Germany","U-Bahn + S-Bahn",["Hamburg"],""),
("Hanover","Germany","Stadtbahn",["Hanover","Hannover"],""),
("Heidelberg","Germany","Trams (RNV)",["Heidelberg"],""),
("Heilbronn","Germany","Stadtbahn (Karlsruhe model, street-running)",["Heilbronn"],""),
("Jena","Germany","Trams",["Jena"],""),
("Karlsruhe","Germany","Trams + Stadtbahn",["Karlsruhe"],""),
("Kassel","Germany","Trams + RegioTram",["Kassel"],""),
("Krefeld","Germany","Trams",["Krefeld"],""),
("Leipzig","Germany","Trams + S-Bahn",["Leipzig"],""),
("Magdeburg","Germany","Trams",["Magdeburg"],""),
("Mainz","Germany","Trams",["Mainz"],""),
("Mannheim","Germany","Trams (RNV)",["Mannheim"],""),
("Ludwigshafen","Germany","Trams (RNV)",["Ludwigshafen"],"S"),
("Mülheim an der Ruhr","Germany","Trams + Stadtbahn U18",["Mülheim","Mulheim","Muelheim"],""),
("Oberhausen","Germany","Trams (line 112)",["Oberhausen"],"S"),
("Munich","Germany","U-Bahn, S-Bahn, trams",["Munich","München","Munchen","Muenchen"],""),
("Naumburg","Germany","Heritage tram",["Naumburg"],"H"),
("Nordhausen","Germany","Trams",["Nordhausen"],""),
("Nuremberg","Germany","U-Bahn + trams",["Nuremberg","Nürnberg","Nurnberg","Nuernberg"],""),
("Fürth","Germany","Nuremberg U-Bahn U1",["Fürth","Furth"],"S"),
("Plauen","Germany","Trams",["Plauen"],""),
("Potsdam","Germany","Trams",["Potsdam"],""),
("Rostock","Germany","Trams",["Rostock"],""),
("Saarbrücken","Germany","Saarbahn",["Saarbrücken","Saarbrucken","Saarbruecken"],""),
("Schwerin","Germany","Trams",["Schwerin"],""),
("Strausberg","Germany","Strausberg Railway (tram)",["Strausberg"],""),
("Woltersdorf","Germany","Woltersdorf tramway",["Woltersdorf"],""),
("Schöneiche","Germany","Schöneiche–Rüdersdorf tramway",["Schöneiche","Schoneiche","Rüdersdorf"],""),
("Stuttgart","Germany","Stadtbahn + S-Bahn",["Stuttgart"],""),
("Ulm","Germany","Trams",["Ulm"],""),
("Würzburg","Germany","Trams",["Würzburg","Wurzburg","Wuerzburg"],""),
("Zwickau","Germany","Trams",["Zwickau"],""),
("Wuppertal","Germany","Schwebebahn (suspended monorail)",["Wuppertal"],""),
("Herne","Germany","Stadtbahn U35",["Herne"],"S"),
("Neuss","Germany","Düsseldorf Stadtbahn U75 / tram 709",["Neuss"],"S"),
# Austria
("Vienna","Austria","U-Bahn + trams",["Vienna","Wien"],""),
("Graz","Austria","Trams",["Graz"],""),
("Linz","Austria","Trams",["Linz"],""),
("Innsbruck","Austria","Trams",["Innsbruck"],""),
("Gmunden","Austria","Traunseetram",["Gmunden","Traunsee"],""),
("Baden bei Wien","Austria","Badner Bahn",["Baden bei Wien","Badner Bahn"],"S"),
# Switzerland
("Basel","Switzerland","Trams (BVB, BLT)",["Basel","Bâle"],""),
("Bern","Switzerland","Trams",["Bern","Berne"],""),
("Geneva","Switzerland","Trams",["Geneva","Genève","Geneve","Genf"],""),
("Lausanne","Switzerland","Metro M1/M2",["Lausanne"],""),
("Neuchâtel","Switzerland","Littorail tram",["Neuchâtel","Neuchatel"],""),
("Zurich","Switzerland","Trams",["Zurich","Zürich"],""),
# Netherlands
("Amsterdam","Netherlands","Metro + trams",["Amsterdam"],""),
("Rotterdam","Netherlands","Metro + trams",["Rotterdam"],""),
("Den Haag","Netherlands","Trams + RandstadRail",["Den Haag","The Hague","'s-Gravenhage"],""),
("Utrecht","Netherlands","Sneltram",["Utrecht"],""),
("Nieuwegein","Netherlands","Utrecht sneltram",["Nieuwegein"],"S"),
("Amstelveen","Netherlands","Amsterdam tram 25",["Amstelveen"],"S"),
("Delft","Netherlands","HTM trams",["Delft"],"S"),
("Rijswijk","Netherlands","HTM trams",["Rijswijk"],"S"),
("Zoetermeer","Netherlands","RandstadRail",["Zoetermeer"],"S"),
# Denmark
("Copenhagen","Denmark","Metro + S-tog",["Copenhagen","København","Kobenhavn"],""),
("Greater Copenhagen Light Rail (Lyngby, Gladsaxe, Herlev, Glostrup, Brøndby, Albertslund, Høje-Taastrup, Ishøj)","Denmark","Hovedstadens Letbane (2025)",["Hovedstadens Letbane","Greater Copenhagen Light Rail","Ring 3","Lyngby","Gladsaxe","Herlev","Glostrup","Ishøj","Høje-Taastrup","Albertslund","Brøndby"],"S"),
("Aarhus","Denmark","Letbane",["Aarhus","Århus"],""),
("Odense","Denmark","Letbane",["Odense"],""),
# Sweden
("Stockholm","Sweden","Tunnelbana + trams",["Stockholm"],""),
("Göteborg","Sweden","Trams",["Göteborg","Goteborg","Gothenburg"],""),
("Lund","Sweden","Lund tramway (2020)",["Lund"],""),
("Norrköping","Sweden","Trams",["Norrköping","Norrkoping"],""),
("Malmö","Sweden","Heritage tram only",["Malmö","Malmo"],"H"),
("Malmköping","Sweden","Museum tram",["Malmköping"],"H"),
# Norway
("Oslo","Norway","T-bane + trams",["Oslo"],""),
("Bergen","Norway","Bybanen",["Bergen"],""),
("Trondheim","Norway","Gråkallbanen tram",["Trondheim"],""),
# Finland
("Helsinki","Finland","Metro + trams",["Helsinki","Helsingfors"],""),
("Espoo","Finland","Länsimetro + Jokeri light rail",["Espoo"],"S"),
("Tampere","Finland","Tampere light rail (2021)",["Tampere"],""),
("Vantaa","Finland","Jokeri light rail; Vantaa tram u/c",["Vantaa"],"S"),
# Baltics
("Tallinn","Estonia","Trams",["Tallinn"],""),
("Riga","Latvia","Trams",["Riga","Rīga"],""),
("Daugavpils","Latvia","Trams",["Daugavpils"],""),
("Liepāja","Latvia","Trams",["Liepāja","Liepaja"],""),
# Poland
("Warsaw","Poland","Metro + trams",["Warsaw","Warszawa"],""),
("Kraków","Poland","Trams",["Kraków","Krakow","Cracow"],""),
("Łódź","Poland","Trams",["Łódź","Lodz","Łodź"],""),
("Wrocław","Poland","Trams",["Wrocław","Wroclaw"],""),
("Poznań","Poland","Trams (incl. Pestka)",["Poznań","Poznan"],""),
("Gdańsk","Poland","Trams",["Gdańsk","Gdansk"],""),
("Szczecin","Poland","Trams",["Szczecin"],""),
("Bydgoszcz","Poland","Trams",["Bydgoszcz"],""),
("Toruń","Poland","Trams",["Toruń","Torun"],""),
("Katowice","Poland","Silesian Interurbans (Tramwaje Śląskie)",["Katowice","Silesia","Tramwaje Śląskie","Upper Silesia"],""),
("Chorzów, Bytom, Gliwice, Sosnowiec, Zabrze, Ruda Śląska, Dąbrowa Górnicza, Będzin","Poland","Tramwaje Śląskie",["Chorzów","Chorzow","Bytom","Gliwice","Sosnowiec","Zabrze","Ruda Śląska","Dąbrowa Górnicza","Będzin"],"S"),
("Częstochowa","Poland","Trams",["Częstochowa","Czestochowa"],""),
("Olsztyn","Poland","Trams (2015)",["Olsztyn"],""),
("Elbląg","Poland","Trams",["Elbląg","Elblag"],""),
("Gorzów Wielkopolski","Poland","Trams",["Gorzów","Gorzow"],""),
("Grudziądz","Poland","Trams",["Grudziądz","Grudziadz"],""),
("Mrozy","Poland","Heritage horse tram",["Mrozy"],"H"),
# Czechia
("Prague","Czechia","Metro + trams",["Prague","Praha"],""),
("Brno","Czechia","Trams",["Brno"],""),
("Ostrava","Czechia","Trams",["Ostrava"],""),
("Plzeň","Czechia","Trams",["Plzeň","Plzen","Pilsen"],""),
("Olomouc","Czechia","Trams",["Olomouc"],""),
("Liberec","Czechia","Trams",["Liberec"],""),
("Most","Czechia","Trams",["Most (Regional)","Litvínov"],""),
# Slovakia
("Bratislava","Slovakia","Trams",["Bratislava"],""),
("Košice","Slovakia","Trams",["Košice","Kosice"],""),
("Trenčianske Teplice","Slovakia","Heritage interurban",["Trenčianske","Trencianske"],"H"),
# Hungary
("Budapest","Hungary","Metro + trams + HÉV",["Budapest"],""),
("Debrecen","Hungary","Trams",["Debrecen"],""),
("Miskolc","Hungary","Trams",["Miskolc"],""),
("Szeged","Hungary","Trams + tram-train",["Szeged"],""),
("Hódmezővásárhely","Hungary","Tram-train",["Hódmezővásárhely","Hodmezovasarhely"],""),
# Romania
("Bucharest","Romania","Metro + trams",["Bucharest","București","Bucuresti"],""),
("Arad","Romania","Trams",["Arad"],""),
("Brăila","Romania","Trams",["Brăila","Braila"],""),
("Cluj-Napoca","Romania","Trams; metro u/c",["Cluj"],""),
("Craiova","Romania","Trams",["Craiova"],""),
("Galați","Romania","Trams",["Galați","Galati","Galaţi"],""),
("Iași","Romania","Trams",["Iași","Iasi","Iaşi"],""),
("Oradea","Romania","Trams",["Oradea"],""),
("Ploiești","Romania","Trams",["Ploiești","Ploiesti","Ploieşti"],""),
("Reșița","Romania","Trams (reopened)",["Reșița","Resita","Reşiţa"],""),
("Timișoara","Romania","Trams",["Timișoara","Timisoara","Timişoara"],""),
("Botoșani","Romania","Trams",["Botoșani","Botosani"],""),
# Balkans
("Sofia","Bulgaria","Metro + trams",["Sofia"],""),
("Belgrade","Serbia","Trams (metro u/c)",["Belgrade","Beograd"],""),
("Zagreb","Croatia","Trams",["Zagreb"],""),
("Osijek","Croatia","Trams",["Osijek"],""),
("Sarajevo","Bosnia and Herzegovina","Trams",["Sarajevo"],""),
("Athens","Greece","Metro + tram",["Athens","Athína","Athina"],""),
("Thessaloniki","Greece","Metro (2024)",["Thessaloniki","Salonica"],""),
# Italy
("Milan","Italy","Metro + trams",["Milan","Milano"],""),
("Rome","Italy","Metro + trams",["Rome","Roma"],""),
("Florence","Italy","Tramvia",["Florence","Firenze"],""),
("Turin","Italy","Metro + trams",["Turin","Torino"],""),
("Naples","Italy","Metro + trams",["Naples","Napoli"],""),
("Genoa","Italy","Metro",["Genoa","Genova"],""),
("Brescia","Italy","Metro",["Brescia"],""),
("Catania","Italy","Metro",["Catania"],""),
("Bergamo","Italy","TEB light rail",["Bergamo"],""),
("Cagliari","Italy","Metrocagliari light rail",["Cagliari"],""),
("Messina","Italy","Tram",["Messina"],""),
("Venice (Mestre)","Italy","Translohr",["Venice","Venezia","Mestre"],""),
("Padua","Italy","Translohr (SIR)",["Padua","Padova"],""),
("Palermo","Italy","Trams",["Palermo"],""),
("Sassari","Italy","Metrosassari",["Sassari"],""),
("Trieste","Italy","Opicina tramway (suspended)",["Trieste"],""),
("Ritten/Renon","Italy","Rittnerbahn",["Ritten","Renon"],"H"),
("Bologna","Italy","Tram Linea Rossa (u/c)",["Bologna"],"U"),
("Perugia","Italy","Minimetrò people mover",["Perugia"],""),
# Spain
("Madrid","Spain","Metro + Metro Ligero",["Madrid"],""),
("Barcelona","Spain","Metro + trams",["Barcelona"],""),
("Palma","Spain","Metro",["Palma"],""),
("Valencia","Spain","Metrovalencia",["Valencia","València"],""),
("Bilbao","Spain","Metro + tram",["Bilbao"],""),
("Seville","Spain","Metro L1 + MetroCentro",["Seville","Sevilla"],""),
("Málaga","Spain","Metro",["Málaga","Malaga"],""),
("Alicante","Spain","TRAM",["Alicante","Alacant"],""),
("Zaragoza","Spain","Tram",["Zaragoza"],""),
("Granada","Spain","Metro (light rail)",["Granada"],""),
("Murcia","Spain","Tram",["Murcia"],""),
("Vitoria-Gasteiz","Spain","Tram",["Vitoria"],""),
("Santa Cruz de Tenerife / La Laguna","Spain","Metrotenerife",["Santa Cruz","Tenerife","La Laguna"],""),
("Cádiz (Chiclana, San Fernando)","Spain","Tram-train (2022)",["Cádiz","Cadiz","Chiclana","San Fernando"],""),
("Parla","Spain","Tram",["Parla"],"S"),
("Jaén","Spain","Tram (reopened 2025?)",["Jaén","Jaen"],""),
("Sóller","Spain","Heritage tram",["Sóller","Soller"],"H"),
# Portugal
("Lisbon","Portugal","Metro + trams",["Lisbon","Lisboa"],""),
("Porto","Portugal","Metro do Porto (light rail)",["Porto"],""),
("Almada / Seixal","Portugal","Metro Transportes do Sul",["Almada","Seixal"],""),
("Vila Nova de Gaia / Matosinhos / Maia","Portugal","Metro do Porto",["Gaia","Matosinhos","Maia"],"S"),
("Sintra","Portugal","Heritage tram",["Sintra"],"H"),
# UK, Ireland, Luxembourg
("London","United Kingdom","Underground etc",["London"],""),
("Glasgow","United Kingdom","Subway",["Glasgow"],""),
("Newcastle","United Kingdom","Tyne and Wear Metro",["Newcastle"],""),
("Manchester","United Kingdom","Metrolink",["Manchester"],""),
("Birmingham","United Kingdom","West Midlands Metro",["Birmingham"],""),
("Edinburgh","United Kingdom","Trams",["Edinburgh"],""),
("Sheffield","United Kingdom","Supertram",["Sheffield"],""),
("Nottingham","United Kingdom","NET",["Nottingham"],""),
("Blackpool","United Kingdom","Tramway",["Blackpool"],""),
("Liverpool","United Kingdom","Merseyrail (commuter)",["Liverpool"],""),
("Seaton","United Kingdom","Heritage tram",["Seaton"],"H"),
("Wirral (Birkenhead)","United Kingdom","Heritage tram",["Wirral","Birkenhead"],"H"),
("Douglas (Isle of Man)","Isle of Man","Horse tram, Manx Electric",["Isle of Man","Douglas","Manx"],"H"),
("Dublin","Ireland","Luas + DART",["Dublin"],""),
("Luxembourg","Luxembourg","Tram (2017)",["Luxembourg"],""),
# Belarus
("Minsk","Belarus","Metro + trams",["Minsk"],""),
("Vitebsk","Belarus","Trams",["Vitebsk","Viciebsk"],""),
("Mazyr","Belarus","Tram",["Mazyr","Mozyr"],""),
("Navapolatsk","Belarus","Tram",["Navapolatsk","Novopolotsk"],""),
# Ukraine
("Kyiv","Ukraine","Metro + trams",["Kyiv","Kiev"],""),
("Kharkiv","Ukraine","Metro + trams",["Kharkiv","Kharkov"],""),
("Dnipro","Ukraine","Metro + trams",["Dnipro","Dnepr"],""),
("Kryvyi Rih","Ukraine","Metrotram + trams",["Kryvyi Rih","Krivoy Rog"],""),
("Lviv","Ukraine","Trams",["Lviv","Lvov","Lwów"],""),
("Odesa","Ukraine","Trams",["Odesa","Odessa"],""),
("Zaporizhzhia","Ukraine","Trams",["Zaporizhzhia","Zaporozhye"],""),
("Mykolaiv","Ukraine","Trams",["Mykolaiv","Nikolaev"],""),
("Vinnytsia","Ukraine","Trams",["Vinnytsia","Vinnitsa"],""),
("Zhytomyr","Ukraine","Tram",["Zhytomyr"],""),
("Konotop","Ukraine","Tram",["Konotop"],""),
("Kamianske","Ukraine","Trams",["Kamianske"],""),
("Donetsk","Ukraine (occupied)","Trams",["Donetsk"],""),
("Horlivka","Ukraine (occupied)","Trams",["Horlivka"],""),
("Yenakiieve","Ukraine (occupied)","Trams",["Yenakiieve"],""),
("Druzhkivka","Ukraine","Trams",["Druzhkivka"],""),
("Mariupol","Ukraine (occupied)","Trams",["Mariupol"],""),
("Yevpatoria","Ukraine (Crimea, occupied)","Trams",["Yevpatoria"],""),
# Russia
("Moscow","Russia","Metro + MCC + trams",["Moscow"],""),
("Saint Petersburg","Russia","Metro + trams",["Saint Petersburg","St Petersburg","St. Petersburg"],""),
("Nizhny Novgorod","Russia","Metro + trams",["Nizhny Novgorod"],""),
("Novosibirsk","Russia","Metro + trams",["Novosibirsk"],""),
("Samara","Russia","Metro + trams",["Samara"],""),
("Yekaterinburg","Russia","Metro + trams",["Yekaterinburg","Ekaterinburg"],""),
("Kazan","Russia","Metro + trams",["Kazan"],""),
("Volgograd","Russia","Metrotram + trams",["Volgograd"],""),
("Achinsk","Russia","Trams",["Achinsk"],""),("Angarsk","Russia","Trams",["Angarsk"],""),
("Barnaul","Russia","Trams",["Barnaul"],""),("Biysk","Russia","Trams",["Biysk"],""),
("Chelyabinsk","Russia","Trams",["Chelyabinsk"],""),("Cherepovets","Russia","Trams",["Cherepovets"],""),
("Cheryomushki","Russia","Tram",["Cheryomushki"],""),("Irkutsk","Russia","Trams",["Irkutsk"],""),
("Izhevsk","Russia","Trams",["Izhevsk"],""),("Kaliningrad","Russia","Trams",["Kaliningrad"],""),
("Kemerovo","Russia","Trams",["Kemerovo"],""),("Khabarovsk","Russia","Trams",["Khabarovsk"],""),
("Kolomna","Russia","Trams",["Kolomna"],""),("Krasnodar","Russia","Trams",["Krasnodar"],""),
("Krasnoturyinsk","Russia","Trams",["Krasnoturyinsk"],""),("Krasnoyarsk","Russia","Trams",["Krasnoyarsk"],""),
("Kursk","Russia","Trams",["Kursk"],""),("Lipetsk","Russia","Trams",["Lipetsk"],""),
("Magnitogorsk","Russia","Trams",["Magnitogorsk"],""),("Naberezhnye Chelny","Russia","Trams",["Naberezhnye Chelny"],""),
("Nizhnekamsk","Russia","Trams",["Nizhnekamsk"],""),("Nizhny Tagil","Russia","Trams",["Nizhny Tagil"],""),
("Novocherkassk","Russia","Trams",["Novocherkassk"],""),("Novokuznetsk","Russia","Trams",["Novokuznetsk"],""),
("Novotroitsk","Russia","Trams",["Novotroitsk"],""),("Omsk","Russia","Trams",["Omsk"],""),
("Orsk","Russia","Trams",["Orsk"],""),("Oryol","Russia","Trams",["Oryol","Orel"],""),
("Osinniki","Russia","Trams",["Osinniki"],""),("Perm","Russia","Trams",["Perm"],""),
("Prokopyevsk","Russia","Trams",["Prokopyevsk"],""),("Pyatigorsk","Russia","Trams",["Pyatigorsk"],""),
("Rostov-on-Don","Russia","Trams",["Rostov"],""),("Salavat","Russia","Trams",["Salavat"],""),
("Saratov","Russia","Trams",["Saratov"],""),("Smolensk","Russia","Trams",["Smolensk"],""),
("Stary Oskol","Russia","Light rail",["Stary Oskol"],""),("Taganrog","Russia","Trams",["Taganrog"],""),
("Tomsk","Russia","Trams",["Tomsk"],""),("Tula","Russia","Trams",["Tula"],""),
("Ufa","Russia","Trams",["Ufa"],""),("Ulan-Ude","Russia","Trams",["Ulan-Ude"],""),
("Ulyanovsk","Russia","Trams",["Ulyanovsk"],""),("Usolye-Sibirskoye","Russia","Trams",["Usolye"],""),
("Vladikavkaz","Russia","Trams",["Vladikavkaz"],""),("Vladivostok","Russia","Trams",["Vladivostok"],""),
("Volchansk","Russia","Tram",["Volchansk"],""),("Volzhsky","Russia","Trams",["Volzhsky"],""),
("Yaroslavl","Russia","Trams",["Yaroslavl"],""),("Zlatoust","Russia","Trams",["Zlatoust"],""),
# Turkiye
("Istanbul","Türkiye","Metro + trams + Marmaray",["Istanbul","İstanbul"],""),
("Ankara","Türkiye","Metro + Ankaray",["Ankara"],""),
("İzmir","Türkiye","Metro + trams + İZBAN",["İzmir","Izmir"],""),
("Bursa","Türkiye","Bursaray + trams",["Bursa"],""),
("Adana","Türkiye","Metro",["Adana"],""),
("Antalya","Türkiye","AntRay light rail + trams",["Antalya"],""),
("Eskişehir","Türkiye","EsTram",["Eskişehir","Eskisehir"],""),
("Gaziantep","Türkiye","Light rail + Gaziray",["Gaziantep"],""),
("Kocaeli (İzmit)","Türkiye","Akçaray tram",["Kocaeli","İzmit","Izmit","Akçaray"],""),
("Kayseri","Türkiye","Kayseray",["Kayseri"],""),
("Konya","Türkiye","Tram",["Konya"],""),
("Samsun","Türkiye","Samulaş light rail",["Samsun"],""),
("Gebze","Türkiye","Gebze–Darıca metro (u/c)",["Gebze"],"U"),
("Mersin","Türkiye","Metro (u/c)",["Mersin"],"U"),
# Caucasus
("Tbilisi","Georgia","Metro",["Tbilisi"],""),
("Baku","Azerbaijan","Metro",["Baku","Bakı"],""),
("Yerevan","Armenia","Metro",["Yerevan"],""),
]
